{
 "title": "Quilkin General Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Traffic [$interval]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quilkin_session_tx_bytes_total[$interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(increase(quilkin_session_rx_bytes_total[$interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Errors [$interval]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(quilkin_session_tx_errors_total[$interval]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(rate(quilkin_session_rx_errors_total[$interval]))",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "Quilkin Instances & Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "count(sum(quilkin_cluster_active{}) by (instance))",
     "legendFormat": "instances"
    },
    {
     "expr": "sum(quilkin_cluster_active_endpoints)",
     "legendFormat": "endpoints"
    },
    { "expr": "sum(quilkin_session_active)", "legendFormat": "active_sessions" }
   ]
  },
  {
   "title": "Network Traffic Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(quilkin_session_tx_bytes_total[$__rate_interval]))",
     "legendFormat": "transmit rate"
    },
    {
     "expr": "sum(rate(quilkin_session_rx_bytes_total[$__rate_interval]))",
     "legendFormat": "receive rate"
    },
    {
     "expr": "sum(rate(quilkin_proxy_packets_dropped_total[$__rate_interval]))",
     "legendFormat": "dropped packet rate"
    },
    {
     "expr": "sum(rate(quilkin_session_rx_errors_total[$__rate_interval]))",
     "legendFormat": "receive error rate"
    },
    {
     "expr": "sum(rate(quilkin_session_tx_errors_total[$__rate_interval]))",
     "legendFormat": "transmit error rate"
    }
   ]
  },
  {
   "title": "Session Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.5,sum(rate(quilkin_session_duration_secs_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": " histogram_quantile(0.9,sum(rate(quilkin_session_duration_secs_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": " histogram_quantile(0.99,sum(rate(quilkin_session_duration_secs_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Packet Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "(total) 50%"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "(total) 90%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "(total) 99%"
    },
    {
     "expr": "histogram_quantile(0.5,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket{event=\"read\"}[$__rate_interval])) by (le))",
     "legendFormat": "(read) 50%"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket{event=\"read\"}[$__rate_interval])) by (le))",
     "legendFormat": "(read) 90%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket{event=\"read\"}[$__rate_interval])) by (le))",
     "legendFormat": "(read) 99%"
    },
    {
     "expr": "histogram_quantile(0.5,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket{event=\"write\"}[$__rate_interval])) by (le))",
     "legendFormat": "(write) 50%"
    },
    {
     "expr": "histogram_quantile(0.9,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket{event=\"write\"}[$__rate_interval])) by (le))",
     "legendFormat": "(write) 90%"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(quilkin_proxy_packet_processing_duration_seconds_bucket{event=\"write\"}[$__rate_interval])) by (le))",
     "legendFormat": "(write) 99%"
    }
   ]
  }
 ]
}