//
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: filters/capture_bytes/v1alpha1/capture_bytes.proto

package quilkin_extensions_filters_capture_bytes_v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CaptureBytes_Strategy int32

const (
	CaptureBytes_Prefix CaptureBytes_Strategy = 0
	CaptureBytes_Suffix CaptureBytes_Strategy = 1
)

// Enum value maps for CaptureBytes_Strategy.
var (
	CaptureBytes_Strategy_name = map[int32]string{
		0: "Prefix",
		1: "Suffix",
	}
	CaptureBytes_Strategy_value = map[string]int32{
		"Prefix": 0,
		"Suffix": 1,
	}
)

func (x CaptureBytes_Strategy) Enum() *CaptureBytes_Strategy {
	p := new(CaptureBytes_Strategy)
	*p = x
	return p
}

func (x CaptureBytes_Strategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CaptureBytes_Strategy) Descriptor() protoreflect.EnumDescriptor {
	return file_filters_capture_bytes_v1alpha1_capture_bytes_proto_enumTypes[0].Descriptor()
}

func (CaptureBytes_Strategy) Type() protoreflect.EnumType {
	return &file_filters_capture_bytes_v1alpha1_capture_bytes_proto_enumTypes[0]
}

func (x CaptureBytes_Strategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CaptureBytes_Strategy.Descriptor instead.
func (CaptureBytes_Strategy) EnumDescriptor() ([]byte, []int) {
	return file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescGZIP(), []int{0, 0}
}

type CaptureBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Strategy    *CaptureBytes_StrategyValue `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Size        uint32                      `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	MetadataKey *wrapperspb.StringValue     `protobuf:"bytes,3,opt,name=metadata_key,json=metadataKey,proto3" json:"metadata_key,omitempty"`
	Remove      *wrapperspb.BoolValue       `protobuf:"bytes,4,opt,name=remove,proto3" json:"remove,omitempty"`
}

func (x *CaptureBytes) Reset() {
	*x = CaptureBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureBytes) ProtoMessage() {}

func (x *CaptureBytes) ProtoReflect() protoreflect.Message {
	mi := &file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureBytes.ProtoReflect.Descriptor instead.
func (*CaptureBytes) Descriptor() ([]byte, []int) {
	return file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescGZIP(), []int{0}
}

func (x *CaptureBytes) GetStrategy() *CaptureBytes_StrategyValue {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *CaptureBytes) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *CaptureBytes) GetMetadataKey() *wrapperspb.StringValue {
	if x != nil {
		return x.MetadataKey
	}
	return nil
}

func (x *CaptureBytes) GetRemove() *wrapperspb.BoolValue {
	if x != nil {
		return x.Remove
	}
	return nil
}

type CaptureBytes_StrategyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value CaptureBytes_Strategy `protobuf:"varint,1,opt,name=value,proto3,enum=quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes_Strategy" json:"value,omitempty"`
}

func (x *CaptureBytes_StrategyValue) Reset() {
	*x = CaptureBytes_StrategyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureBytes_StrategyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureBytes_StrategyValue) ProtoMessage() {}

func (x *CaptureBytes_StrategyValue) ProtoReflect() protoreflect.Message {
	mi := &file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureBytes_StrategyValue.ProtoReflect.Descriptor instead.
func (*CaptureBytes_StrategyValue) Descriptor() ([]byte, []int) {
	return file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CaptureBytes_StrategyValue) GetValue() CaptureBytes_Strategy {
	if x != nil {
		return x.Value
	}
	return CaptureBytes_Prefix
}

var File_filters_capture_bytes_v1alpha1_capture_bytes_proto protoreflect.FileDescriptor

var file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDesc = []byte{
	0x0a, 0x32, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x31, 0x71, 0x75, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2e, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x03, 0x0a, 0x0c, 0x43, 0x61, 0x70, 0x74,
	0x75, 0x72, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x69, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4d, 0x2e, 0x71, 0x75, 0x69,
	0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x43,
	0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x3f, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x4b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x1a, 0x6f, 0x0a, 0x0d,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x5e, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x48, 0x2e, 0x71,
	0x75, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x2e, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a,
	0x08, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x10,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescOnce sync.Once
	file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescData = file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDesc
)

func file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescGZIP() []byte {
	file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescOnce.Do(func() {
		file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescData)
	})
	return file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDescData
}

var file_filters_capture_bytes_v1alpha1_capture_bytes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filters_capture_bytes_v1alpha1_capture_bytes_proto_goTypes = []interface{}{
	(CaptureBytes_Strategy)(0),         // 0: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.Strategy
	(*CaptureBytes)(nil),               // 1: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes
	(*CaptureBytes_StrategyValue)(nil), // 2: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.StrategyValue
	(*wrapperspb.StringValue)(nil),     // 3: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),       // 4: google.protobuf.BoolValue
}
var file_filters_capture_bytes_v1alpha1_capture_bytes_proto_depIdxs = []int32{
	2, // 0: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.strategy:type_name -> quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.StrategyValue
	3, // 1: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.metadata_key:type_name -> google.protobuf.StringValue
	4, // 2: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.remove:type_name -> google.protobuf.BoolValue
	0, // 3: quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.StrategyValue.value:type_name -> quilkin.extensions.filters.capture_bytes.v1alpha1.CaptureBytes.Strategy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_filters_capture_bytes_v1alpha1_capture_bytes_proto_init() }
func file_filters_capture_bytes_v1alpha1_capture_bytes_proto_init() {
	if File_filters_capture_bytes_v1alpha1_capture_bytes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureBytes_StrategyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_capture_bytes_v1alpha1_capture_bytes_proto_goTypes,
		DependencyIndexes: file_filters_capture_bytes_v1alpha1_capture_bytes_proto_depIdxs,
		EnumInfos:         file_filters_capture_bytes_v1alpha1_capture_bytes_proto_enumTypes,
		MessageInfos:      file_filters_capture_bytes_v1alpha1_capture_bytes_proto_msgTypes,
	}.Build()
	File_filters_capture_bytes_v1alpha1_capture_bytes_proto = out.File
	file_filters_capture_bytes_v1alpha1_capture_bytes_proto_rawDesc = nil
	file_filters_capture_bytes_v1alpha1_capture_bytes_proto_goTypes = nil
	file_filters_capture_bytes_v1alpha1_capture_bytes_proto_depIdxs = nil
}
