//
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: filters/load_balancer/v1alpha1/load_balancer.proto

package quilkin_extensions_filters_load_balancer_v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LoadBalancer_Policy int32

const (
	LoadBalancer_RoundRobin LoadBalancer_Policy = 0
	LoadBalancer_Random     LoadBalancer_Policy = 1
)

// Enum value maps for LoadBalancer_Policy.
var (
	LoadBalancer_Policy_name = map[int32]string{
		0: "RoundRobin",
		1: "Random",
	}
	LoadBalancer_Policy_value = map[string]int32{
		"RoundRobin": 0,
		"Random":     1,
	}
)

func (x LoadBalancer_Policy) Enum() *LoadBalancer_Policy {
	p := new(LoadBalancer_Policy)
	*p = x
	return p
}

func (x LoadBalancer_Policy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancer_Policy) Descriptor() protoreflect.EnumDescriptor {
	return file_filters_load_balancer_v1alpha1_load_balancer_proto_enumTypes[0].Descriptor()
}

func (LoadBalancer_Policy) Type() protoreflect.EnumType {
	return &file_filters_load_balancer_v1alpha1_load_balancer_proto_enumTypes[0]
}

func (x LoadBalancer_Policy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancer_Policy.Descriptor instead.
func (LoadBalancer_Policy) EnumDescriptor() ([]byte, []int) {
	return file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescGZIP(), []int{0, 0}
}

type LoadBalancer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policy *LoadBalancer_PolicyValue `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
}

func (x *LoadBalancer) Reset() {
	*x = LoadBalancer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancer) ProtoMessage() {}

func (x *LoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancer.ProtoReflect.Descriptor instead.
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescGZIP(), []int{0}
}

func (x *LoadBalancer) GetPolicy() *LoadBalancer_PolicyValue {
	if x != nil {
		return x.Policy
	}
	return nil
}

type LoadBalancer_PolicyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value LoadBalancer_Policy `protobuf:"varint,1,opt,name=value,proto3,enum=quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer_Policy" json:"value,omitempty"`
}

func (x *LoadBalancer_PolicyValue) Reset() {
	*x = LoadBalancer_PolicyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadBalancer_PolicyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancer_PolicyValue) ProtoMessage() {}

func (x *LoadBalancer_PolicyValue) ProtoReflect() protoreflect.Message {
	mi := &file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancer_PolicyValue.ProtoReflect.Descriptor instead.
func (*LoadBalancer_PolicyValue) Descriptor() ([]byte, []int) {
	return file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoadBalancer_PolicyValue) GetValue() LoadBalancer_Policy {
	if x != nil {
		return x.Value
	}
	return LoadBalancer_RoundRobin
}

var File_filters_load_balancer_v1alpha1_load_balancer_proto protoreflect.FileDescriptor

var file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDesc = []byte{
	0x0a, 0x32, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x31, 0x71, 0x75, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x22, 0x86, 0x02, 0x0a, 0x0c, 0x4c, 0x6f, 0x61, 0x64,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x63, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x71, 0x75, 0x69, 0x6c, 0x6b,
	0x69, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x1a, 0x6b, 0x0a,
	0x0b, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x5c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x46, 0x2e, 0x71, 0x75,
	0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x4c, 0x6f, 0x61, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x24, 0x0a, 0x06, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x6f, 0x62,
	0x69, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x10, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescOnce sync.Once
	file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescData = file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDesc
)

func file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescGZIP() []byte {
	file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescOnce.Do(func() {
		file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescData)
	})
	return file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDescData
}

var file_filters_load_balancer_v1alpha1_load_balancer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_filters_load_balancer_v1alpha1_load_balancer_proto_goTypes = []interface{}{
	(LoadBalancer_Policy)(0),         // 0: quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer.Policy
	(*LoadBalancer)(nil),             // 1: quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer
	(*LoadBalancer_PolicyValue)(nil), // 2: quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer.PolicyValue
}
var file_filters_load_balancer_v1alpha1_load_balancer_proto_depIdxs = []int32{
	2, // 0: quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer.policy:type_name -> quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer.PolicyValue
	0, // 1: quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer.PolicyValue.value:type_name -> quilkin.extensions.filters.load_balancer.v1alpha1.LoadBalancer.Policy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_filters_load_balancer_v1alpha1_load_balancer_proto_init() }
func file_filters_load_balancer_v1alpha1_load_balancer_proto_init() {
	if File_filters_load_balancer_v1alpha1_load_balancer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadBalancer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadBalancer_PolicyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_load_balancer_v1alpha1_load_balancer_proto_goTypes,
		DependencyIndexes: file_filters_load_balancer_v1alpha1_load_balancer_proto_depIdxs,
		EnumInfos:         file_filters_load_balancer_v1alpha1_load_balancer_proto_enumTypes,
		MessageInfos:      file_filters_load_balancer_v1alpha1_load_balancer_proto_msgTypes,
	}.Build()
	File_filters_load_balancer_v1alpha1_load_balancer_proto = out.File
	file_filters_load_balancer_v1alpha1_load_balancer_proto_rawDesc = nil
	file_filters_load_balancer_v1alpha1_load_balancer_proto_goTypes = nil
	file_filters_load_balancer_v1alpha1_load_balancer_proto_depIdxs = nil
}
