//
// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: filters/debug/v1alpha1/debug.proto

package quilkin_extensions_filters_debug_v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Debug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Debug) Reset() {
	*x = Debug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_debug_v1alpha1_debug_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Debug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debug) ProtoMessage() {}

func (x *Debug) ProtoReflect() protoreflect.Message {
	mi := &file_filters_debug_v1alpha1_debug_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debug.ProtoReflect.Descriptor instead.
func (*Debug) Descriptor() ([]byte, []int) {
	return file_filters_debug_v1alpha1_debug_proto_rawDescGZIP(), []int{0}
}

func (x *Debug) GetId() *wrapperspb.StringValue {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_filters_debug_v1alpha1_debug_proto protoreflect.FileDescriptor

var file_filters_debug_v1alpha1_debug_proto_rawDesc = []byte{
	0x0a, 0x22, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x29, 0x71, 0x75, 0x69, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x65, 0x78,
	0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73,
	0x2e, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x35, 0x0a, 0x05, 0x44, 0x65, 0x62, 0x75, 0x67, 0x12, 0x2c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x02, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_debug_v1alpha1_debug_proto_rawDescOnce sync.Once
	file_filters_debug_v1alpha1_debug_proto_rawDescData = file_filters_debug_v1alpha1_debug_proto_rawDesc
)

func file_filters_debug_v1alpha1_debug_proto_rawDescGZIP() []byte {
	file_filters_debug_v1alpha1_debug_proto_rawDescOnce.Do(func() {
		file_filters_debug_v1alpha1_debug_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_debug_v1alpha1_debug_proto_rawDescData)
	})
	return file_filters_debug_v1alpha1_debug_proto_rawDescData
}

var file_filters_debug_v1alpha1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_filters_debug_v1alpha1_debug_proto_goTypes = []interface{}{
	(*Debug)(nil),                  // 0: quilkin.extensions.filters.debug.v1alpha1.Debug
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
}
var file_filters_debug_v1alpha1_debug_proto_depIdxs = []int32{
	1, // 0: quilkin.extensions.filters.debug.v1alpha1.Debug.id:type_name -> google.protobuf.StringValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_filters_debug_v1alpha1_debug_proto_init() }
func file_filters_debug_v1alpha1_debug_proto_init() {
	if File_filters_debug_v1alpha1_debug_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_debug_v1alpha1_debug_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Debug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_debug_v1alpha1_debug_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_debug_v1alpha1_debug_proto_goTypes,
		DependencyIndexes: file_filters_debug_v1alpha1_debug_proto_depIdxs,
		MessageInfos:      file_filters_debug_v1alpha1_debug_proto_msgTypes,
	}.Build()
	File_filters_debug_v1alpha1_debug_proto = out.File
	file_filters_debug_v1alpha1_debug_proto_rawDesc = nil
	file_filters_debug_v1alpha1_debug_proto_goTypes = nil
	file_filters_debug_v1alpha1_debug_proto_depIdxs = nil
}
